app = "{{ project_name }}"
primary_region = 'lax'
kill_signal = 'SIGINT'
kill_timeout = 30
console_command = '/code/manage.py shell'

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
